apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app2
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28
        ports:
          - containerPort: 80
            name: http-nginx
      - name: multitool
        image: wbitt/network-multitool
        ports:
          - containerPort: 11443
            name: https-multitool
        env:
          - name: HTTP_PORT
            value: '1180'
          - name: HTTPS_PORT
            value: '11443'
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 2
       maxSurge: 5
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  namespace: app2
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-http
    protocol: TCP
    port: 80
    targetPort: http-nginx
