apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: 12-03
  labels:
    app: nginx
spec:
  containers:
  - name: multitool2
    image: wbitt/network-multitool
    env:
      - name: HTTP_PORT
        value: '2280'
      - name: HTTPS_PORT 
        value: '22443'


