apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
  namespace: 12-07
spec:
  storageClassName: "nfs"
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
     storage: 1Gi
