apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
  namespace: 12-07
spec:
  storageClassName: ""
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
     storage: 1Gi
