---
- name: Install Clickhouse
  hosts: clickhouse-01
      roles:
      - clickhouse
    tags: clickhouse
- name: Install Vector
  hosts: vector-01
      roles:
      - vector-role
    tags: vector
- name: Install Lighthouse
  hosts: lighthouse-01
      roles:
      - lighthouse
    tags: lighthouse